//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetireHappy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public string password { get; set; }
        public string userName { get; set; }
    
        public virtual ExpenditureList ExpenditureList { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
