//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetireHappy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int mId { get; set; }

        [Display(Name = "Password", Prompt = "Password")]
        [Required(ErrorMessage = "Please enter password")]
        [StringLength(255, MinimumLength = 8)]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [Display(Name = "Username", Prompt = "Username")]
        [Required(ErrorMessage = "Please enter username")]
        [StringLength(30, MinimumLength = 6)]
        public string userName { get; set; }
    
        public virtual ExpenditureList ExpenditureList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
