//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetireHappy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserProfile
    {
        public int Id { get; set; }
        public Nullable<int> mId { get; set; }
        [Display(Name = "What is your age?")]
        [Range(12, 99)]
        [Required]
        public Nullable<int> age { get; set; }

        [Display(Name = "What is your gender?")]
        [Required(ErrorMessage = "Please select your gender")]
        public string gender { get; set; }

        [Display(Name = "Your Expected Retirement Age")]
        [Range(18, 99)]
        [Required]
        public Nullable<int> expRetAge { get; set; }

        [Display(Name = "Retirement Duration(years)")]
        [Range(1, 99)]
        public Nullable<int> retDuration { get; set; }

        [Display(Name = "Your Monthly Take Home Pay")]
        [Range(0d, (double)decimal.MaxValue, ErrorMessage = "Amount must be greater than zero.")]
        [Required]
        public Nullable<double> monIncome { get; set; }

        [Display(Name = "Monthly Expenditure")]
        [Range(0d, (double)decimal.MaxValue, ErrorMessage = "Amount must be greater than zero.")]
        public Nullable<double> avgMonExpenditure { get; set; }

        [Display(Name = "Current Monthly Savings Amount")]
        [Required]
        [Range(0d, (double)decimal.MaxValue, ErrorMessage = "Amount must be greater than zero.")]
        public Nullable<double> curSavingAmt { get; set; }

        [Display(Name = "Desired Monthly Retirement Income")]
        [Range(0d, (double)decimal.MaxValue, ErrorMessage = "Amount must be greater than zero.")]
        [Required]
        public Nullable<double> desiredMonRetInc { get; set; }

        [Display(Name = "Departure Date")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yy}", ApplyFormatInEditMode = true)]
        [Required]
        public Nullable<System.DateTime> timestamp { get; set; }

        [Display(Name = "Inflation Rate")]
        [Required]
        public Nullable<double> inflationRate { get; set; }

        public string ifUseAvgExp { get; set; }

        public virtual Member Member { get; set; }
        public virtual SavingsInfo SavingsInfo { get; set; }
    }
}
