//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetireHappy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int Id { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public Nullable<int> expRetAge { get; set; }
        public Nullable<int> retDuration { get; set; }
        public Nullable<double> monIncome { get; set; }
        public Nullable<double> avgMonExpenditure { get; set; }
        public Nullable<double> curSavingAmt { get; set; }
        public Nullable<double> desiredMonRetInc { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<double> inflationRate { get; set; }
    
        public virtual SavingsInfo SavingsInfo { get; set; }
    }
}
